const test = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
function setup() {
 const records = new Map([['users/admin',{role:'admin'}],['users/buyer',{role:'customer'}],['items/shop',{kind:'agent',ownerId:'seller',title:'Test',mediatorFee:10,deliveryFee:5}]]);
 let counter=0;
 const ref = path => ({path,id:path.split('/').pop(),collection:n=>({doc:id=>ref(`${path}/${n}/${id || ++counter}`)}),get:async()=>({data:()=>records.get(path)})});
 const db={doc:ref,collection:n=>({doc:id=>ref(`${n}/${id || ++counter}`)}),runTransaction:async cb=>{
  const writes=[]; const result=await cb({get:async r=>({exists:records.has(r.path),data:()=>records.get(r.path)}),create:(r,d)=>writes.push(()=>{assert(!records.has(r.path));records.set(r.path,d)}),update:(r,d)=>writes.push(()=>records.set(r.path,{...records.get(r.path),...d})),delete:r=>writes.push(()=>records.delete(r.path))});writes.forEach(w=>w());return result;
 }};
 class HttpsError extends Error {constructor(code,message){super(message);this.code=code}}
 const context={exports:{},require:name=> name==='firebase-functions/v2/https'?{onCall:f=>f,HttpsError}:name==='firebase-admin/firestore'?{getFirestore:()=>db,FieldValue:{serverTimestamp:()=>123}}:name==='./mediator-core.cjs'?require('./mediator-core.cjs'):require(name)};
 vm.runInNewContext(fs.readFileSync(`${__dirname}/mediator.js`,'utf8'),context);
 const call=(uid,action,data={})=>context.exports.mediatorAction({auth:uid?{uid}:null,data:{action,...data}});
 const create=()=>call('buyer','create',{businessId:'shop',requestId:'abcdefghijklmnop',paymentMethod:'cash',details:'groceries',address:'address',budget:80,expectedFeeCents:1000,expectedDeliveryCents:500});
 return {records,call,create};
}
test('authentication, card and price tampering rejected',async()=>{const s=setup();await assert.rejects(s.call(null,'create')); await assert.rejects(s.call('buyer','create',{businessId:'shop',requestId:'abcdefghijklmnop',paymentMethod:'card'}));s.records.get('items/shop').mediatorFee=12;await assert.rejects(s.create());});
test('agreement fixes 5% commission and includes the concrete example',async()=>{const s=setup();const terms=await s.call('buyer','terms');assert.equal(terms.commissionBps,500);assert.match(terms.contractText,/20 ₪/);assert.match(terms.contractText,/1 ₪/);assert.match(terms.contractText,/19 ₪/);const result=await s.call('buyer','apply',{name:'Mediator',phone:'+970 599 000000',area:'Hebron',latitude:31.53,longitude:35.1,agreementVersion:terms.agreementVersion,acceptPrivacy:true,acceptContract:true});assert.equal(result.status,'pending');assert.equal(s.records.get('mediator_applications/buyer').commissionBps,500);});
test('idempotent create; participant-only acceptance; delivery once; settlement reference',async()=>{const s=setup();const {orderId}=await s.create();assert.equal((await s.create()).orderId,orderId);await assert.rejects(s.call('stranger','accept',{orderId}));await assert.rejects(s.call('buyer','accept',{orderId}));await s.call('seller','accept',{orderId});await assert.rejects(s.call('seller','reject',{orderId}));const path=`mediator_orders/${orderId}`;const otp=s.records.get(`${path}/private/delivery`).otp;assert.match(otp,/^\d{6}$/);await assert.rejects(s.call('seller','deliver',{orderId,otp,cashCollected:false}));await s.call('seller','deliver',{orderId,otp,cashCollected:true});assert.equal(s.records.get(path).earningStatus,'due');assert(!s.records.has(`${path}/private/delivery`));await assert.rejects(s.call('seller','deliver',{orderId,otp,cashCollected:true}));await assert.rejects(s.call('admin','settle',{orderId}));await s.call('admin','settle',{orderId,note:'transfer 123'});assert.equal(s.records.get(path).earningStatus,'paid');});
test('order snapshots commission and net fee',async()=>{const s=setup();const {orderId}=await s.create();const order=s.records.get(`mediator_orders/${orderId}`);assert.equal(order.platformFeeCents,50);assert.equal(order.netFeeCents,950);assert.equal(order.commissionBps,500);});
test('wrong OTP persists attempt count and never accrues earnings',async()=>{const s=setup();const {orderId}=await s.create();await s.call('seller','accept',{orderId});await assert.rejects(s.call('seller','deliver',{orderId,otp:'wrong',cashCollected:true}));assert.equal(s.records.get(`mediator_orders/${orderId}/private/delivery`).attempts,1);assert.equal(s.records.get(`mediator_orders/${orderId}`).earningStatus,'pending');});
test('dispute holds only selected order; admin resolution restores prior state',async()=>{const s=setup();const {orderId}=await s.create();await s.call('seller','accept',{orderId});s.records.set('mediator_orders/other',{earningStatus:'due'});await s.call('buyer','dispute',{orderId,note:'missing purchase'});assert.equal(s.records.get(`mediator_orders/${orderId}`).earningStatus,'held');assert.equal(s.records.get('mediator_orders/other').earningStatus,'due');await assert.rejects(s.call('seller','resolve',{orderId,note:'resolved'}));await assert.rejects(s.call('admin','settle',{orderId,note:'transfer'}));await s.call('admin','resolve',{orderId,note:'reviewed'});assert.equal(s.records.get(`mediator_orders/${orderId}`).status,'in_progress');});
