// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vUPyQHotiybswHkP5bAXqrXIkggM0Us',
    appId: '1:783945761203:web:b66000463fd51c8b684bc6',
    messagingSenderId: '783945761203',
    projectId: 'barakah-new',
    authDomain: 'barakah-new.firebaseapp.com',
    storageBucket: 'barakah-new.firebasestorage.app',
    measurementId: 'G-9XDBPWGXV7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClco57MParkblTbc-DoM4mVDFJhsBfMcY',
    appId: '1:783945761203:ios:99eabaa743ef42cb684bc6',
    messagingSenderId: '783945761203',
    projectId: 'barakah-new',
    storageBucket: 'barakah-new.firebasestorage.app',
    iosBundleId: 'com.barakah.market',
  );
}
